In [1]:
import requests
import pandas as pd
import requests
from datetime import datetime, timedelta, timezone
import json
import numpy as np
import re
import os
from openpyxl import load_workbook
import warnings

Mounted at /content/drive

In [2]:
SHOP = "247andco"
ACCESS_TOKEN_SHOP = "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"
ACCESS_TOKEN_FB = "EAANo2IL9c9YBRS2fv5vlLa2fIMJlUvtQfKI0aFDahCSQxmnZCW1ZCtmDeiXr2vLjuRZAqMCpckYZCKPcBjS8wv3Bjq9sWZC0L2mIrRLoCwqO7GPf9KwWznQJQ5e933bBIgP8cv0aDKb3GZC8onjPLwqH5phz0hXXL9IdTqQ4dASqpIxsADZANya0o95hPOtSOkJ"
AD_ACCOUNT_ID = ["act_366408762460670", "act_926575882092645", "act_5834593206593509", "act_2729625483948255", "act_743322649818898"]

In [3]:
# IST timezone
ist = timezone(timedelta(hours=5, minutes=30))

# Today IST (as a *string*)
today_ist = datetime.now(ist).strftime("%Y-%m-%d")

# Yesterday IST (as a *string*)
yesterday_ist = (datetime.now(ist) - timedelta(days=1)).strftime("%Y-%m-%d")

print("Today IST:", today_ist)
print("Yesterday IST:", yesterday_ist)

# Use this in your API call
date_str = today_ist

Today IST: 2026-06-11
Yesterday IST: 2026-06-10

In [4]:
# --- Input IST date ---
date_str = yesterday_ist
# date_str = '2026-06-10'
# change this to any date you want

In [5]:
#Get FB AD Data

FIELDS = (
    "campaign_id,campaign_name,spend,impressions,clicks,"
    "date_start,date_stop,results, created_time, updated_time"
)

def get_insights(ad_account_id):
    url = f"https://graph.facebook.com/v23.0/{ad_account_id}/insights"
    params = {
        "access_token": ACCESS_TOKEN_FB,
        "level": "campaign",
          "time_range": json.dumps({
        "since": date_str,
        "until": date_str
    }),
        # "date_preset": "last_3d",
        "fields": FIELDS,
        "limit": 5000
    }
    r = requests.get(url, params=params).json()
    df = pd.DataFrame(r.get("data", []))
    df["ad_account_id"] = ad_account_id
    return df

# Fetch + combine
dfs = [get_insights(acc) for acc in AD_ACCOUNT_ID]
df = pd.concat(dfs, ignore_index=True)

# --- Flatten results ---
def flatten_results(results):
    out = {}
    if isinstance(results, list):
        for r in results:
            indicator = r.get("indicator", "").replace("actions:", "").replace(".", "_")
            values = r.get("values", [])
            if values:
                out[indicator] = values[0].get("value")
    return out

if "results" in df.columns:
    results_df = df["results"].apply(flatten_results).apply(pd.Series)
    df = pd.concat([df.drop(columns=["results"]), results_df], axis=1)

# --- Rename common metrics ---
rename_map = {
    "offsite_conversion_fb_pixel_purchase": "purchase_pixel",
    "link_click": "link_click",
    "lead": "lead"
}
df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns}, inplace=True)

# --- Convert numeric columns ---
for col in ["spend", "impressions", "clicks", "purchase_pixel", "lead", "link_click"]:
    if col in df.columns and isinstance(df[col], pd.Series):
        df[col] = pd.to_numeric(df[col], errors="coerce")

# --- Calculate cost metrics ---
if "purchase_pixel" in df.columns:
    df["cpp"] = (df["spend"] / df["purchase_pixel"]).round(2)

if "lead" in df.columns:
    df["cpl"] = (df["spend"] / df["lead"]).round(2)

if "link_click" in df.columns:
    df["cpc_link"] = (df["spend"] / df["link_click"]).round(2)

meta_df = df.reset_index(drop=True)
# meta_df["join_label"] = (
#     meta_df["campaign_name"]
#     .str.split("--").str[-1]        # take text after --
#     .str.strip()                    # remove spaces
#     .str.replace(r"\s+", " ", regex=True)
#     .str.lower()                    # lowercase
# )
meta_df["join_label"] = (
    meta_df["campaign_name"]
    .astype(str)
    .str.replace(r"(?i)\s*[-()]*\s*copy\s*\d*$", "", regex=True)  # remove "copy", "- copy", "(copy)", "copy 2"
    .str.split("--").str[-1]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.lower()
)
pd.set_option("display.max_colwidth", None)
meta_df.sort_values("updated_time", ascending=False)

,ad_account_id,campaign_id,campaign_name,spend,impressions,clicks,date_start,date_stop,created_time,updated_time,purchase_pixel,cpp,join_label
98,act_743322649818898,120252654729140102,3--Shiatsu Foot Massager,0.00,0,0,2026-06-10,2026-06-10,2026-06-10,2026-06-10,NaN,NaN,shiatsu foot massager
54,act_743322649818898,120252004766090102,TIK TOK 6--mini cycle pedal exerciser,62.38,883,9,2026-06-10,2026-06-10,2026-06-01,2026-06-10,1.0,62.38,mini cycle pedal exerciser
15,act_926575882092645,120247006005130165,15 -- Sweat Slim Belt,451.67,2048,17,2026-06-10,2026-06-10,2026-06-09,2026-06-10,1.0,451.67,sweat slim belt
14,act_926575882092645,120247006005100165,10 --Sweat Slim Belt,454.09,1631,18,2026-06-10,2026-06-10,2026-06-09,2026-06-10,NaN,NaN,sweat slim belt
19,act_926575882092645,120247006005430165,belt 2 --Sweat Slim Belt,475.54,2325,15,2026-06-10,2026-06-10,2026-06-09,2026-06-10,2.0,237.77,sweat slim belt
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,act_926575882092645,120246289764800165,tik tok 13-- 3-in-1 Postpartum Belly Belt,1709.91,5322,106,2026-06-10,2026-06-10,2026-05-29,2026-06-04,3.0,569.97,3-in-1 postpartum belly belt
5,act_926575882092645,120246289764760165,belt 2-- 3-in-1 Postpartum Belly Belt,1771.18,8086,193,2026-06-10,2026-06-10,2026-05-29,2026-06-04,1.0,1771.18,3-in-1 postpartum belly belt
4,act_926575882092645,120245912720250165,ayushi -- 3-in-1 Postpartum Belly Belt,1996.58,18061,173,2026-06-10,2026-06-10,2026-05-24,2026-06-04,6.0,332.76,3-in-1 postpartum belly belt
3,act_926575882092645,120245753501700165,cbo AD4 +7+ss5re+sss2+1-- Sweat Slim Belt,2903.40,13385,217,2026-06-10,2026-06-10,2026-05-22,2026-06-04,7.0,414.77,sweat slim belt
42,act_2729625483948255,120244136168440574,winner combine cbo-- 3-in-1 Postpartum Belly Belt,1446.11,11664,123,2026-06-10,2026-06-10,2026-05-25,2026-06-03,NaN,NaN,3-in-1 postpartum belly belt

In [6]:
#Get SHOPIFY Sales Data

def graphql(query, variables=None):
    if variables is None:
        variables = {}

    url = f"https://{SHOP}.myshopify.com/admin/api/2025-01/graphql.json"
    headers = {
        "Content-Type": "application/json",
        "X-Shopify-Access-Token": ACCESS_TOKEN_SHOP,
    }

    response = requests.post(url, json={"query": query, "variables": variables}, headers=headers)

    print("Status:", response.status_code)
    print("Body:", response.text)

    return response.json()


# --- Fetch ALL orders using pagination ---
all_orders = []
cursor = None
has_next_page = True

while has_next_page:
    query = f"""
    query getOrders($cursor: String) {{
      orders(
        first: 250,
        after: $cursor,
        query: "created_at:>={date_str} created_at:<={date_str}"
      ) {{
        pageInfo {{
          hasNextPage
          endCursor
        }}
        edges {{
          node {{
            id
            createdAt
            totalTaxSet {{
              shopMoney {{ amount }}
            }}
            lineItems(first: 50) {{
              edges {{
                node {{
                  title
                  quantity
                  product {{
                    vendor
                    productType
                  }}
                  originalUnitPriceSet {{
                    shopMoney {{ amount }}
                  }}
                  discountedUnitPriceSet {{
                    shopMoney {{ amount }}
                  }}
                }}
              }}
            }}
          }}
        }}
      }}
    }}
    """

    data = graphql(query, {"cursor": cursor})
    orders = data["data"]["orders"]

    all_orders.extend(orders["edges"])

    has_next_page = orders["pageInfo"]["hasNextPage"]
    cursor = orders["pageInfo"]["endCursor"]

print(f"Total orders fetched: {len(all_orders)}")


# --- Aggregate by product title ---
product_stats = {}

for order_edge in all_orders:
    order = order_edge["node"]
    order_tax = float(order["totalTaxSet"]["shopMoney"]["amount"])

    for item_edge in order["lineItems"]["edges"]:
        item = item_edge["node"]

        title = item["title"]
        qty = item["quantity"]

        price = float(item["originalUnitPriceSet"]["shopMoney"]["amount"])
        discounted_price = float(item["discountedUnitPriceSet"]["shopMoney"]["amount"])

        gross = price * qty
        net = discounted_price * qty

        if title not in product_stats:
            product_stats[title] = {
                "product_title": title,
                "units_sold": 0,
                "total_sales": 0,
                "selling_price": discounted_price,
            }

        product_stats[title]["units_sold"] += qty
        product_stats[title]["total_sales"] += net + order_tax


# --- Convert to DataFrame ---
df = pd.DataFrame(product_stats.values())

# --- Sort by units sold ---
df_shop = df.sort_values("units_sold", ascending=False).reset_index(drop=True)

df_shop

Status: 200

,product_title,units_sold,total_sales,selling_price
0,Upyogaa 3-in-1 Postpartum Belly Belt | Medical-Grade Fabric | Breathable | Skin Friendly| 1 Year Warranty,53,84747.00,1599.00
1,Upyogaa Vibration Plate Massager Home & Gym Workout Machine For Muscle Toning |Calorie Burning | Massaging |Weight Loss |Pain Relief |Max Load 180 kg | 1 Year Warranty,41,266459.00,6499.00
2,"UPYOGAA Sweat Slim Belt for Men & Women | Neoprene Tummy Trimmer Belt for Fat Loss, Stomach Shaping & Workout Support | Adjustable Waist Trainer Sauna Belt for Gym, Yoga & Daily Use",34,47566.00,1399.00
3,"Upyogaa Mini Cycle Pedal Exerciser with Fixing Strap, Adjustable Resistance and Digital Display - Suitable for Light Exercise of Legs, Arms, and Physiotherapy at Home ,High Strength Steel Frame,1 Year Warranty",17,50983.00,2999.00
4,"UPYOGAA Yoga Pedal Puller Resistance Band ,1 Year Warranty",12,19188.00,1599.00
5,"Belly Fat Burner Electric Abdominal Slimming Belt with Vibration & Heat, Belly Massager & Muscle Stimulator Belt for Stomach Toning, Body Shaper Fitness Belt for Men & Women Home Use | 1 year Warranty",10,14990.00,1499.00
6,"Upyogaa Shiatsu Foot Massager Machine with Heat, Foot and Calf Massager,Delivers Relief for Tired Muscles and Plantar,Deep Tissue Massager, Pain Relief, Promotes Blood Circulation Gift for Women Men| 1 year Warranty.",7,20993.00,2999.00
7,Upyogaa Bunion Corrector for Women Men | 1 year warranty,5,8995.00,1799.00
8,Upyogaa Thigh Trainer & Kegel Exerciser | Resilient 16 kg Inner Thigh & Pelvic Floor Strengthener | Postpartum Recovery | High Grade Material |,4,5520.00,1380.00
9,"Impact Breathing by Upyogaa – Breathe Better, Live Better",3,1047.00,349.00
10,Upyogaa Heating Pad for Period Cramps Built with Hand Warmer Pocket | 1 year Warranty,3,5997.00,1999.00
11,"Upyogaa Health & Fitness Mini Stepper for Exercise at Home, Stair Step Workout Machine ,180KG Weight Capacity,1 Year Warranty",3,10797.00,3599.00
12,Postpartum Belly Belt,2,3198.00,1599.00
13,Smart Cupping Massager PRO,1,2999.00,2999.00
14,Vibration Plate Exerciser & Massager,1,6499.00,6499.00
15,Tip,1,29.99,29.99
16,Upyogaa Premium Detox Foot Pads – Cleansing & Remover Patches,1,799.00,799.00

# Clean Up

In [7]:
join_labels = (
    meta_df["join_label"]
    .dropna()
    .unique()
    .tolist())

In [8]:
join_labels

['3-in-1 postpartum belly belt',
 'impact',
 'yoga pedal puller resistance band',
 'sweat slim belt',
 'belly fat burner',
 'bunion corrector for women men',
 'heating pad for period cramps',
 'thigh trainer & kegel exerciser',
 'mini cycle pedal exerciser',
 'vibration plate massager',
 'health & fitness mini stepper for exercise',
 'shiatsu foot massager']

In [9]:
grouped_meta_df = meta_df.groupby('join_label').agg(
    total_campaigns=('campaign_name', 'count'),
    total_spend=('spend', 'sum'),
    purchase_pixel_meta=('purchase_pixel', 'sum')
).reset_index()

display(grouped_meta_df)

,join_label,total_campaigns,total_spend,purchase_pixel_meta
0,3-in-1 postpartum belly belt,11,25847.32,47.0
1,belly fat burner,5,1788.05,6.0
2,bunion corrector for women men,5,2447.65,5.0
3,health & fitness mini stepper for exercise,5,3104.90,3.0
4,heating pad for period cramps,5,2255.02,3.0
5,impact,1,758.29,4.0
6,mini cycle pedal exerciser,14,6160.02,17.0
7,shiatsu foot massager,4,2055.17,7.0
8,sweat slim belt,21,14570.97,27.0
9,thigh trainer & kegel exerciser,1,788.56,4.0
10,vibration plate massager,25,20392.99,36.0
11,yoga pedal puller resistance band,2,4434.78,15.0

In [11]:
# def best_label_with_tiebreak(title, labels, threshold=100):
#     scores = []

#     for lbl in labels:
#         score = fuzz.token_set_ratio(title.lower(), lbl.lower())
#         if score >= threshold:
#             scores.append((lbl, score))

#     if not scores:
#         return "Other"

#     # Step 1: find highest score
#     max_score = max(s[1] for s in scores)

#     # Step 2: filter labels with that score
#     tied = [lbl for lbl, sc in scores if sc == max_score]

#     # Step 3: tie-break by longest label
#     best = max(tied, key=len)

#     return best

In [12]:
# def detect_join_label(title, labels, threshold=100):
#     """
#     Fuzzy match product title to join_labels.
#     - Uses token_set_ratio
#     - Handles ties
#     - Prefers longest (most specific) label
#     - Prints a warning when ties occur
#     """

#     title = title.lower()
#     scores = []

#     # Compute fuzzy score for each label
#     for lbl in labels:
#         score = fuzz.token_set_ratio(title, lbl.lower())
#         if score >= threshold:
#             scores.append((lbl, score))

#     # No matches
#     if not scores:
#         return "Other"

#     # Find highest score
#     max_score = max(s[1] for s in scores)

#     # All labels that tied with the highest score
#     tied = [lbl for lbl, sc in scores if sc == max_score]

#     # If tie detected → warn
#     if len(tied) > 1:
#         print(f"⚠️ Warning: Tie detected for title='{title}' → {tied}")

#     # Tie-breaker: choose the longest (most specific) label
#     best_label = max(tied, key=len)

#     return best_label

In [10]:
def detect_join_label(title, labels):
    t = title.lower()

    # clean labels
    labels = [lbl.strip().lower() for lbl in labels]

    # find matches
    matches = [lbl for lbl in labels if lbl in t]
    matches = list(set(matches))  # remove duplicates

    if len(matches) == 0:
        return "Other"

    if len(matches) > 1:
        warnings.warn(
            f"Multiple join_labels matched for product_title='{title}': {matches}",
            UserWarning
        )
        # choose first match deterministically
        return matches[0]

    return matches[0]

In [11]:
df_shop["join_label"] = df_shop["product_title"].apply(
    lambda x: detect_join_label(x, join_labels)
)
df_shop

,product_title,units_sold,total_sales,selling_price,join_label
0,Upyogaa 3-in-1 Postpartum Belly Belt | Medical-Grade Fabric | Breathable | Skin Friendly| 1 Year Warranty,53,84747.00,1599.00,3-in-1 postpartum belly belt
1,Upyogaa Vibration Plate Massager Home & Gym Workout Machine For Muscle Toning |Calorie Burning | Massaging |Weight Loss |Pain Relief |Max Load 180 kg | 1 Year Warranty,41,266459.00,6499.00,vibration plate massager
2,"UPYOGAA Sweat Slim Belt for Men & Women | Neoprene Tummy Trimmer Belt for Fat Loss, Stomach Shaping & Workout Support | Adjustable Waist Trainer Sauna Belt for Gym, Yoga & Daily Use",34,47566.00,1399.00,sweat slim belt
3,"Upyogaa Mini Cycle Pedal Exerciser with Fixing Strap, Adjustable Resistance and Digital Display - Suitable for Light Exercise of Legs, Arms, and Physiotherapy at Home ,High Strength Steel Frame,1 Year Warranty",17,50983.00,2999.00,mini cycle pedal exerciser
4,"UPYOGAA Yoga Pedal Puller Resistance Band ,1 Year Warranty",12,19188.00,1599.00,yoga pedal puller resistance band
5,"Belly Fat Burner Electric Abdominal Slimming Belt with Vibration & Heat, Belly Massager & Muscle Stimulator Belt for Stomach Toning, Body Shaper Fitness Belt for Men & Women Home Use | 1 year Warranty",10,14990.00,1499.00,belly fat burner
6,"Upyogaa Shiatsu Foot Massager Machine with Heat, Foot and Calf Massager,Delivers Relief for Tired Muscles and Plantar,Deep Tissue Massager, Pain Relief, Promotes Blood Circulation Gift for Women Men| 1 year Warranty.",7,20993.00,2999.00,shiatsu foot massager
7,Upyogaa Bunion Corrector for Women Men | 1 year warranty,5,8995.00,1799.00,bunion corrector for women men
8,Upyogaa Thigh Trainer & Kegel Exerciser | Resilient 16 kg Inner Thigh & Pelvic Floor Strengthener | Postpartum Recovery | High Grade Material |,4,5520.00,1380.00,thigh trainer & kegel exerciser
9,"Impact Breathing by Upyogaa – Breathe Better, Live Better",3,1047.00,349.00,impact
10,Upyogaa Heating Pad for Period Cramps Built with Hand Warmer Pocket | 1 year Warranty,3,5997.00,1999.00,heating pad for period cramps
11,"Upyogaa Health & Fitness Mini Stepper for Exercise at Home, Stair Step Workout Machine ,180KG Weight Capacity,1 Year Warranty",3,10797.00,3599.00,health & fitness mini stepper for exercise
12,Postpartum Belly Belt,2,3198.00,1599.00,Other
13,Smart Cupping Massager PRO,1,2999.00,2999.00,Other
14,Vibration Plate Exerciser & Massager,1,6499.00,6499.00,Other
15,Tip,1,29.99,29.99,Other
16,Upyogaa Premium Detox Foot Pads – Cleansing & Remover Patches,1,799.00,799.00,Other

In [13]:
df_merged = pd.merge(df_shop, grouped_meta_df, on='join_label', how='outer')
df_merged

,product_title,units_sold,total_sales,selling_price,join_label,total_campaigns,total_spend,purchase_pixel_meta
0,Upyogaa 3-in-1 Postpartum Belly Belt | Medical-Grade Fabric | Breathable | Skin Friendly| 1 Year Warranty,53,84747.00,1599.00,3-in-1 postpartum belly belt,11.0,25847.32,47.0
1,Postpartum Belly Belt,2,3198.00,1599.00,Other,NaN,NaN,NaN
2,Smart Cupping Massager PRO,1,2999.00,2999.00,Other,NaN,NaN,NaN
3,Vibration Plate Exerciser & Massager,1,6499.00,6499.00,Other,NaN,NaN,NaN
4,Tip,1,29.99,29.99,Other,NaN,NaN,NaN
5,Upyogaa Premium Detox Foot Pads – Cleansing & Remover Patches,1,799.00,799.00,Other,NaN,NaN,NaN
6,"Belly Fat Burner Electric Abdominal Slimming Belt with Vibration & Heat, Belly Massager & Muscle Stimulator Belt for Stomach Toning, Body Shaper Fitness Belt for Men & Women Home Use | 1 year Warranty",10,14990.00,1499.00,belly fat burner,5.0,1788.05,6.0
7,Upyogaa Bunion Corrector for Women Men | 1 year warranty,5,8995.00,1799.00,bunion corrector for women men,5.0,2447.65,5.0
8,"Upyogaa Health & Fitness Mini Stepper for Exercise at Home, Stair Step Workout Machine ,180KG Weight Capacity,1 Year Warranty",3,10797.00,3599.00,health & fitness mini stepper for exercise,5.0,3104.90,3.0
9,Upyogaa Heating Pad for Period Cramps Built with Hand Warmer Pocket | 1 year Warranty,3,5997.00,1999.00,heating pad for period cramps,5.0,2255.02,3.0
10,"Impact Breathing by Upyogaa – Breathe Better, Live Better",3,1047.00,349.00,impact,1.0,758.29,4.0
11,"Upyogaa Mini Cycle Pedal Exerciser with Fixing Strap, Adjustable Resistance and Digital Display - Suitable for Light Exercise of Legs, Arms, and Physiotherapy at Home ,High Strength Steel Frame,1 Year Warranty",17,50983.00,2999.00,mini cycle pedal exerciser,14.0,6160.02,17.0
12,"Upyogaa Shiatsu Foot Massager Machine with Heat, Foot and Calf Massager,Delivers Relief for Tired Muscles and Plantar,Deep Tissue Massager, Pain Relief, Promotes Blood Circulation Gift for Women Men| 1 year Warranty.",7,20993.00,2999.00,shiatsu foot massager,4.0,2055.17,7.0
13,"UPYOGAA Sweat Slim Belt for Men & Women | Neoprene Tummy Trimmer Belt for Fat Loss, Stomach Shaping & Workout Support | Adjustable Waist Trainer Sauna Belt for Gym, Yoga & Daily Use",34,47566.00,1399.00,sweat slim belt,21.0,14570.97,27.0
14,Upyogaa Thigh Trainer & Kegel Exerciser | Resilient 16 kg Inner Thigh & Pelvic Floor Strengthener | Postpartum Recovery | High Grade Material |,4,5520.00,1380.00,thigh trainer & kegel exerciser,1.0,788.56,4.0
15,Upyogaa Vibration Plate Massager Home & Gym Workout Machine For Muscle Toning |Calorie Burning | Massaging |Weight Loss |Pain Relief |Max Load 180 kg | 1 Year Warranty,41,266459.00,6499.00,vibration plate massager,25.0,20392.99,36.0
16,"UPYOGAA Yoga Pedal Puller Resistance Band ,1 Year Warranty",12,19188.00,1599.00,yoga pedal puller resistance band,2.0,4434.78,15.0

In [14]:
print(df_merged['total_spend'].sum(),
meta_df['spend'].sum())

print(df_merged['total_campaigns'].sum(),
meta_df['campaign_id'].count())

84603.72 84603.72
99.0 99

In [15]:
df_final = df_merged.copy()
df_final['unit_price'] = df_final['total_sales'] / df_final['units_sold']
df_final['roas'] = df_final['total_sales'] / df_final['total_spend']
df_final['cpp'] = df_final['total_spend'] / df_final['units_sold']
df_final["Date"] = date_str
df_final = df_final.rename(columns={
    "product_title": "Product Name",
    "units_sold": "Sales/Orders",
    "unit_price": "Unit Price",
    "total_sales": "Revenue",
    "join_label": "Join Label",
    "total_campaigns": "Total Campaigns",
    "total_spend": "Total Ad Spend",
    "roas": "ROAS",
    "cpp": "CPP",
    "selling_price": "Selling Price"
}
)[["Product Name","Join Label", "Selling Price",
   "Total Campaigns","Total Ad Spend", "Revenue", "Sales/Orders", "CPP", "ROAS", "Date"]
  ].round(1).fillna("")

df_final

,Product Name,Join Label,Selling Price,Total Campaigns,Total Ad Spend,Revenue,Sales/Orders,CPP,ROAS,Date
0,Upyogaa 3-in-1 Postpartum Belly Belt | Medical-Grade Fabric | Breathable | Skin Friendly| 1 Year Warranty,3-in-1 postpartum belly belt,1599.0,11.0,25847.3,84747.0,53,487.7,3.3,2026-06-10
1,Postpartum Belly Belt,Other,1599.0,,,3198.0,2,,,2026-06-10
2,Smart Cupping Massager PRO,Other,2999.0,,,2999.0,1,,,2026-06-10
3,Vibration Plate Exerciser & Massager,Other,6499.0,,,6499.0,1,,,2026-06-10
4,Tip,Other,30.0,,,30.0,1,,,2026-06-10
5,Upyogaa Premium Detox Foot Pads – Cleansing & Remover Patches,Other,799.0,,,799.0,1,,,2026-06-10
6,"Belly Fat Burner Electric Abdominal Slimming Belt with Vibration & Heat, Belly Massager & Muscle Stimulator Belt for Stomach Toning, Body Shaper Fitness Belt for Men & Women Home Use | 1 year Warranty",belly fat burner,1499.0,5.0,1788.0,14990.0,10,178.8,8.4,2026-06-10
7,Upyogaa Bunion Corrector for Women Men | 1 year warranty,bunion corrector for women men,1799.0,5.0,2447.6,8995.0,5,489.5,3.7,2026-06-10
8,"Upyogaa Health & Fitness Mini Stepper for Exercise at Home, Stair Step Workout Machine ,180KG Weight Capacity,1 Year Warranty",health & fitness mini stepper for exercise,3599.0,5.0,3104.9,10797.0,3,1035.0,3.5,2026-06-10
9,Upyogaa Heating Pad for Period Cramps Built with Hand Warmer Pocket | 1 year Warranty,heating pad for period cramps,1999.0,5.0,2255.0,5997.0,3,751.7,2.7,2026-06-10
10,"Impact Breathing by Upyogaa – Breathe Better, Live Better",impact,349.0,1.0,758.3,1047.0,3,252.8,1.4,2026-06-10
11,"Upyogaa Mini Cycle Pedal Exerciser with Fixing Strap, Adjustable Resistance and Digital Display - Suitable for Light Exercise of Legs, Arms, and Physiotherapy at Home ,High Strength Steel Frame,1 Year Warranty",mini cycle pedal exerciser,2999.0,14.0,6160.0,50983.0,17,362.4,8.3,2026-06-10
12,"Upyogaa Shiatsu Foot Massager Machine with Heat, Foot and Calf Massager,Delivers Relief for Tired Muscles and Plantar,Deep Tissue Massager, Pain Relief, Promotes Blood Circulation Gift for Women Men| 1 year Warranty.",shiatsu foot massager,2999.0,4.0,2055.2,20993.0,7,293.6,10.2,2026-06-10
13,"UPYOGAA Sweat Slim Belt for Men & Women | Neoprene Tummy Trimmer Belt for Fat Loss, Stomach Shaping & Workout Support | Adjustable Waist Trainer Sauna Belt for Gym, Yoga & Daily Use",sweat slim belt,1399.0,21.0,14571.0,47566.0,34,428.6,3.3,2026-06-10
14,Upyogaa Thigh Trainer & Kegel Exerciser | Resilient 16 kg Inner Thigh & Pelvic Floor Strengthener | Postpartum Recovery | High Grade Material |,thigh trainer & kegel exerciser,1380.0,1.0,788.6,5520.0,4,197.1,7.0,2026-06-10
15,Upyogaa Vibration Plate Massager Home & Gym Workout Machine For Muscle Toning |Calorie Burning | Massaging |Weight Loss |Pain Relief |Max Load 180 kg | 1 Year Warranty,vibration plate massager,6499.0,25.0,20393.0,266459.0,41,497.4,13.1,2026-06-10
16,"UPYOGAA Yoga Pedal Puller Resistance Band ,1 Year Warranty",yoga pedal puller resistance band,1599.0,2.0,4434.8,19188.0,12,369.6,4.3,2026-06-10

In [17]:
output_dir = '/content/drive/MyDrive/Colab Notebooks/Upyogaa'
output_path = os.path.join(output_dir, 'upyogaa_reconciler_v2.xlsx')

os.makedirs(output_dir, exist_ok=True)

# --- File must exist ---
if not os.path.exists(output_path):
    raise FileNotFoundError(f"Excel file not found: {output_path}")

# Load workbook
wb = load_workbook(output_path)

# --- Master sheet must exist ---
if 'Master' not in wb.sheetnames:
    raise ValueError("Sheet 'Master' not found in workbook. Aborting — not creating a new sheet.")

ws = wb['Master']

# Convert df_final to list of lists
rows = df_final.values.tolist()

def get_real_last_row(ws, col=1):
    last = 0
    for row in range(1, ws.max_row + 1):
        if ws.cell(row=row, column=col).value not in (None, ""):
            last = row
    return last
start_row = get_real_last_row(ws) + 1

print("Appending at:", start_row)

for r_idx, row in enumerate(rows, start=start_row):
    for c_idx, value in enumerate(row, start=1):
        ws.cell(row=r_idx, column=c_idx, value=value)


# Save workbook
wb.save(output_path)
print("Appended only to Master sheet — all other sheets preserved.")

Appending at: 97
Appended only to Master sheet — all other sheets preserved.

In [16]:
output_dir = '/content/drive/MyDrive/Colab Notebooks/Upyogaa'
output_path = os.path.join(output_dir, 'upyogaa_reconciler_v2.xlsx')

os.makedirs(output_dir, exist_ok=True)

# --- File must exist ---
if not os.path.exists(output_path):
    raise FileNotFoundError(f"Excel file not found: {output_path}")

# Load workbook
wb = load_workbook(output_path)

# --- Master sheet must exist ---
if 'Master' not in wb.sheetnames:
    raise ValueError("Sheet 'Master' not found in workbook. Aborting — not creating a new sheet.")

ws = wb['Master']

# Convert df_final to list of lists
rows = df_final.values.tolist()

def get_real_last_row(ws, col=1):
    last = 0
    for row in range(1, ws.max_row + 1):
        if ws.cell(row=row, column=col).value not in (None, ""):
            last = row
    return last
start_row = get_real_last_row(ws) + 1

print("Appending at:", start_row)

Appending at: 97

/usr/local/lib/python3.12/dist-packages/openpyxl/packaging/relationship.py:118: UserWarning: xl/pivotCache/_rels/pivotCacheDefinition1.xml.rels contains invalid dependency definitions
  warn(msg)